### ISSUE TITLE
Sheath multiple weapons

### ISSUE THREAD

**Issue by arteeh** [SlavicPotato/SimpleDualSheath#2]
Hey, like I said in the other issue, huge fan of this mod.

One thing I'm missing is the ability to carry weapons that aren't currently equipped. For characters that use multiple weapons (eg. sword+shield and bow+arrow, or mage + melee) it's quite unimmersive to watch the unequipped weapon vanish in thin air rather than being placed on the character's back/sheath.

The AllGUD dual sheath mod has a feature where all favourited weapons, staves and shields are shown on the player, and this works pretty well. Could you implement something like this in your mod as well?

**Comment by SlavicPotato** [comment]
I've been working on a separate plugin for displaying unequipped gear and custom models. There's a lot more work involved (UI, papyrus interface for modders, models have to be loaded and managed separately, etc..). 

It's not ready for release yet but you can try out a private beta if you're interested.

**Comment by arteeh** [comment]
I'm interested in the private beta!

**Comment by SlavicPotato** [comment]
You have access to the repo. Use the issue tracker if you have questions!
